"""Add address column to User

Revision ID: 9540e76c977b
Revises: 
Create Date: 2025-01-17 11:20:12.764940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9540e76c977b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
